---
github_owner: naseeb-helali
github_repo: mini-write

github_runner_version: "2.329.0"

github_runner_name: "{{ ansible_hostname }}"

github_runner_labels:
  - self-hosted
  - linux
  - x64
  - staging
  - mini-write

github_runner_install_dir: "/home/{{ deploy_user }}/actions-runner"

github_runner_repo_url: >-
  https://github.com/{{ github_owner }}/{{ github_repo }}

github_runner_api_url: >-
  https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/actions/runners/registration-token

github_runner_archive_name: >-
  actions-runner-linux-x64-{{ github_runner_version }}.tar.gz

github_runner_download_url: >-
  https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/{{ github_runner_archive_name }}

github_runner_archive_path: >-
  /tmp/{{ github_runner_archive_name }}

github_runner_disable_update: true
