apiVersion: 1

contactPoints:

  - orgId: 1

    name: alertmanager

    receivers:

      - uid: alertmanager-receiver

        type: prometheus-alertmanager

        settings:

          url: http://alertmanager:9093